// Code generated by MockGen. DO NOT EDIT.
// Source: internal/service/dep/interfaces.go

// Package mock_dep is a generated GoMock package.
package mock_dep

import (
	context "context"
	reflect "reflect"
	"service-order-avito/internal/domain/model"
	time "time"

	gomock "github.com/golang/mock/gomock"
)

// MockTransactionManager is a mock of TransactionManager interface.
type MockTransactionManager struct {
	ctrl     *gomock.Controller
	recorder *MockTransactionManagerMockRecorder
}

// MockTransactionManagerMockRecorder is the mock recorder for MockTransactionManager.
type MockTransactionManagerMockRecorder struct {
	mock *MockTransactionManager
}

// NewMockTransactionManager creates a new mock instance.
func NewMockTransactionManager(ctrl *gomock.Controller) *MockTransactionManager {
	mock := &MockTransactionManager{ctrl: ctrl}
	mock.recorder = &MockTransactionManagerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTransactionManager) EXPECT() *MockTransactionManagerMockRecorder {
	return m.recorder
}

// Begin mocks base method.
func (m *MockTransactionManager) Begin(arg0 context.Context, arg1 func(context.Context) error) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Begin", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Begin indicates an expected call of Begin.
func (mr *MockTransactionManagerMockRecorder) Begin(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Begin", reflect.TypeOf((*MockTransactionManager)(nil).Begin), arg0, arg1)
}

// MockCourierRepository is a mock of CourierRepository interface.
type MockCourierRepository struct {
	ctrl     *gomock.Controller
	recorder *MockCourierRepositoryMockRecorder
}

// MockCourierRepositoryMockRecorder is the mock recorder for MockCourierRepository.
type MockCourierRepositoryMockRecorder struct {
	mock *MockCourierRepository
}

// NewMockCourierRepository creates a new mock instance.
func NewMockCourierRepository(ctrl *gomock.Controller) *MockCourierRepository {
	mock := &MockCourierRepository{ctrl: ctrl}
	mock.recorder = &MockCourierRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCourierRepository) EXPECT() *MockCourierRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockCourierRepository) Create(arg0 context.Context, arg1 model.Courier) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", arg0, arg1)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockCourierRepositoryMockRecorder) Create(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockCourierRepository)(nil).Create), arg0, arg1)
}

// DeleteById mocks base method.
func (m *MockCourierRepository) DeleteById(arg0 context.Context, arg1 int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteById", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteById indicates an expected call of DeleteById.
func (mr *MockCourierRepositoryMockRecorder) DeleteById(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteById", reflect.TypeOf((*MockCourierRepository)(nil).DeleteById), arg0, arg1)
}

// GetAll mocks base method.
func (m *MockCourierRepository) GetAll(arg0 context.Context) ([]model.Courier, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAll", arg0)
	ret0, _ := ret[0].([]model.Courier)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAll indicates an expected call of GetAll.
func (mr *MockCourierRepositoryMockRecorder) GetAll(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAll", reflect.TypeOf((*MockCourierRepository)(nil).GetAll), arg0)
}

// GetAvailable mocks base method.
func (m *MockCourierRepository) GetAvailable(arg0 context.Context) (model.Courier, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAvailable", arg0)
	ret0, _ := ret[0].(model.Courier)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAvailable indicates an expected call of GetAvailable.
func (mr *MockCourierRepositoryMockRecorder) GetAvailable(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAvailable", reflect.TypeOf((*MockCourierRepository)(nil).GetAvailable), arg0)
}

// GetById mocks base method.
func (m *MockCourierRepository) GetById(arg0 context.Context, arg1 int) (model.Courier, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetById", arg0, arg1)
	ret0, _ := ret[0].(model.Courier)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetById indicates an expected call of GetById.
func (mr *MockCourierRepositoryMockRecorder) GetById(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetById", reflect.TypeOf((*MockCourierRepository)(nil).GetById), arg0, arg1)
}

// Update mocks base method.
func (m *MockCourierRepository) Update(arg0 context.Context, arg1 model.Courier) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockCourierRepositoryMockRecorder) Update(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockCourierRepository)(nil).Update), arg0, arg1)
}

// UpdateStatusManyById mocks base method.
func (m *MockCourierRepository) UpdateStatusManyById(arg0 context.Context, arg1 ...int) error {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0}
	for _, a := range arg1 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "UpdateStatusManyById", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateStatusManyById indicates an expected call of UpdateStatusManyById.
func (mr *MockCourierRepositoryMockRecorder) UpdateStatusManyById(arg0 interface{}, arg1 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0}, arg1...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateStatusManyById", reflect.TypeOf((*MockCourierRepository)(nil).UpdateStatusManyById), varargs...)
}

// MockDeliveryRepository is a mock of DeliveryRepository interface.
type MockDeliveryRepository struct {
	ctrl     *gomock.Controller
	recorder *MockDeliveryRepositoryMockRecorder
}

// MockDeliveryRepositoryMockRecorder is the mock recorder for MockDeliveryRepository.
type MockDeliveryRepositoryMockRecorder struct {
	mock *MockDeliveryRepository
}

// NewMockDeliveryRepository creates a new mock instance.
func NewMockDeliveryRepository(ctrl *gomock.Controller) *MockDeliveryRepository {
	mock := &MockDeliveryRepository{ctrl: ctrl}
	mock.recorder = &MockDeliveryRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDeliveryRepository) EXPECT() *MockDeliveryRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockDeliveryRepository) Create(arg0 context.Context, arg1 model.Delivery) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", arg0, arg1)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockDeliveryRepositoryMockRecorder) Create(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockDeliveryRepository)(nil).Create), arg0, arg1)
}

// DeleteByOrderId mocks base method.
func (m *MockDeliveryRepository) DeleteByOrderId(arg0 context.Context, arg1 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteByOrderId", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteByOrderId indicates an expected call of DeleteByOrderId.
func (mr *MockDeliveryRepositoryMockRecorder) DeleteByOrderId(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteByOrderId", reflect.TypeOf((*MockDeliveryRepository)(nil).DeleteByOrderId), arg0, arg1)
}

// DeleteManyById mocks base method.
func (m *MockDeliveryRepository) DeleteManyById(arg0 context.Context, arg1 ...int) error {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0}
	for _, a := range arg1 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "DeleteManyById", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteManyById indicates an expected call of DeleteManyById.
func (mr *MockDeliveryRepositoryMockRecorder) DeleteManyById(arg0 interface{}, arg1 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0}, arg1...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteManyById", reflect.TypeOf((*MockDeliveryRepository)(nil).DeleteManyById), varargs...)
}

// GetAllCompleted mocks base method.
func (m *MockDeliveryRepository) GetAllCompleted(arg0 context.Context) ([]model.Delivery, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllCompleted", arg0)
	ret0, _ := ret[0].([]model.Delivery)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllCompleted indicates an expected call of GetAllCompleted.
func (mr *MockDeliveryRepositoryMockRecorder) GetAllCompleted(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllCompleted", reflect.TypeOf((*MockDeliveryRepository)(nil).GetAllCompleted), arg0)
}

// GetByOrderId mocks base method.
func (m *MockDeliveryRepository) GetByOrderId(arg0 context.Context, arg1 string) (model.Delivery, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByOrderId", arg0, arg1)
	ret0, _ := ret[0].(model.Delivery)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByOrderId indicates an expected call of GetByOrderId.
func (mr *MockDeliveryRepositoryMockRecorder) GetByOrderId(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByOrderId", reflect.TypeOf((*MockDeliveryRepository)(nil).GetByOrderId), arg0, arg1)
}

// MockDeliveryTimeCalculator is a mock of DeliveryTimeCalculator interface.
type MockDeliveryTimeCalculator struct {
	ctrl     *gomock.Controller
	recorder *MockDeliveryTimeCalculatorMockRecorder
}

// MockDeliveryTimeCalculatorMockRecorder is the mock recorder for MockDeliveryTimeCalculator.
type MockDeliveryTimeCalculatorMockRecorder struct {
	mock *MockDeliveryTimeCalculator
}

// NewMockDeliveryTimeCalculator creates a new mock instance.
func NewMockDeliveryTimeCalculator(ctrl *gomock.Controller) *MockDeliveryTimeCalculator {
	mock := &MockDeliveryTimeCalculator{ctrl: ctrl}
	mock.recorder = &MockDeliveryTimeCalculatorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDeliveryTimeCalculator) EXPECT() *MockDeliveryTimeCalculatorMockRecorder {
	return m.recorder
}

// Calculate mocks base method.
func (m *MockDeliveryTimeCalculator) Calculate(transportType string) time.Time {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Calculate", transportType)
	ret0, _ := ret[0].(time.Time)
	return ret0
}

// Calculate indicates an expected call of Calculate.
func (mr *MockDeliveryTimeCalculatorMockRecorder) Calculate(transportType interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Calculate", reflect.TypeOf((*MockDeliveryTimeCalculator)(nil).Calculate), transportType)
}
