version: "2"

run:
  timeout: 3m
  max-issues-per-linter: 50
  max-same-issues: 50
linters:
  enable:
    - govet
    - staticcheck
    - errcheck
    - unused
    - gocritic
issues:
  exclude-use-default: false