// Code generated by MockGen. DO NOT EDIT.
// Source: internal/http/server/handler/delivery/delivery.go

// Package mock_delivery is a generated GoMock package.
package mock_delivery

import (
	context "context"
	reflect "reflect"
	dto "service-order-avito/internal/domain/dto"

	gomock "github.com/golang/mock/gomock"
)

// MockdeliveryService is a mock of deliveryService interface.
type MockdeliveryService struct {
	ctrl     *gomock.Controller
	recorder *MockdeliveryServiceMockRecorder
}

// MockdeliveryServiceMockRecorder is the mock recorder for MockdeliveryService.
type MockdeliveryServiceMockRecorder struct {
	mock *MockdeliveryService
}

// NewMockdeliveryService creates a new mock instance.
func NewMockdeliveryService(ctrl *gomock.Controller) *MockdeliveryService {
	mock := &MockdeliveryService{ctrl: ctrl}
	mock.recorder = &MockdeliveryServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockdeliveryService) EXPECT() *MockdeliveryServiceMockRecorder {
	return m.recorder
}

// AssignDelivery mocks base method.
func (m *MockdeliveryService) Assign(arg0 context.Context, arg1 *dto.AssignDeliveryRequest) (*dto.AssignDeliveryResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Assign", arg0, arg1)
	ret0, _ := ret[0].(*dto.AssignDeliveryResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AssignDelivery indicates an expected call of AssignDelivery.
func (mr *MockdeliveryServiceMockRecorder) AssignDelivery(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Assign", reflect.TypeOf((*MockdeliveryService)(nil).Assign), arg0, arg1)
}

// UnassignDelivery mocks base method.
func (m *MockdeliveryService) Unassign(arg0 context.Context, arg1 *dto.UnassignDeliveryRequest) (*dto.UnassignDeliveryResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Unassign", arg0, arg1)
	ret0, _ := ret[0].(*dto.UnassignDeliveryResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UnassignDelivery indicates an expected call of UnassignDelivery.
func (mr *MockdeliveryServiceMockRecorder) UnassignDelivery(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Unassign", reflect.TypeOf((*MockdeliveryService)(nil).Unassign), arg0, arg1)
}
