// Code generated by MockGen. DO NOT EDIT.
// Source: internal/http/server/handler/courier/courier.go

// Package mock_courier is a generated GoMock package.
package mock_courier

import (
	context "context"
	reflect "reflect"
	dto "service-order-avito/internal/domain/dto"

	gomock "github.com/golang/mock/gomock"
)

// MockсourierService is a mock of сourierService interface.
type MockсourierService struct {
	ctrl     *gomock.Controller
	recorder *MockсourierServiceMockRecorder
}

// MockсourierServiceMockRecorder is the mock recorder for MockсourierService.
type MockсourierServiceMockRecorder struct {
	mock *MockсourierService
}

// NewMockсourierService creates a new mock instance.
func NewMockсourierService(ctrl *gomock.Controller) *MockсourierService {
	mock := &MockсourierService{ctrl: ctrl}
	mock.recorder = &MockсourierServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockсourierService) EXPECT() *MockсourierServiceMockRecorder {
	return m.recorder
}

// CreateCourier mocks base method.
func (m *MockсourierService) CreateCourier(arg0 context.Context, arg1 *dto.CreateCourierRequest) (*dto.CreateCourierResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateCourier", arg0, arg1)
	ret0, _ := ret[0].(*dto.CreateCourierResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateCourier indicates an expected call of CreateCourier.
func (mr *MockсourierServiceMockRecorder) CreateCourier(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateCourier", reflect.TypeOf((*MockсourierService)(nil).CreateCourier), arg0, arg1)
}

// DeleteCourier mocks base method.
func (m *MockсourierService) DeleteCourier(arg0 context.Context, arg1 *dto.DeleteCourierRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteCourier", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteCourier indicates an expected call of DeleteCourier.
func (mr *MockсourierServiceMockRecorder) DeleteCourier(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteCourier", reflect.TypeOf((*MockсourierService)(nil).DeleteCourier), arg0, arg1)
}

// GetAllCouriers mocks base method.
func (m *MockсourierService) GetAllCouriers(arg0 context.Context) ([]dto.GetCourierResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllCouriers", arg0)
	ret0, _ := ret[0].([]dto.GetCourierResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllCouriers indicates an expected call of GetAllCouriers.
func (mr *MockсourierServiceMockRecorder) GetAllCouriers(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllCouriers", reflect.TypeOf((*MockсourierService)(nil).GetAllCouriers), arg0)
}

// GetCourier mocks base method.
func (m *MockсourierService) GetCourier(arg0 context.Context, arg1 *dto.GetCourierRequest) (*dto.GetCourierResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCourier", arg0, arg1)
	ret0, _ := ret[0].(*dto.GetCourierResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCourier indicates an expected call of GetCourier.
func (mr *MockсourierServiceMockRecorder) GetCourier(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCourier", reflect.TypeOf((*MockсourierService)(nil).GetCourier), arg0, arg1)
}

// UpdateCourier mocks base method.
func (m *MockсourierService) UpdateCourier(arg0 context.Context, arg1 *dto.UpdateCourierRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateCourier", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateCourier indicates an expected call of UpdateCourier.
func (mr *MockсourierServiceMockRecorder) UpdateCourier(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateCourier", reflect.TypeOf((*MockсourierService)(nil).UpdateCourier), arg0, arg1)
}
